default_platform(:android)

# Method to load properties from keystore.properties file
def load_keystore_properties
    properties = {}
    File.open('../app/keystore.properties', 'r') do |file|
        file.each_line do |line|
            key, value = line.split('=')
            properties[key.strip] = value.strip
        end
    end
    properties
end

platform :android do
  desc "Increase version number"
  lane :bump do |options|
    android_set_version_code
    if options[:version] && options[:version] != ""
      android_set_version_name(
        version_name: options[:version]
      )
    end

    # Write version to record file
    version_num = android_get_version_code
    version_name = android_get_version_name
    sh("echo '#{version_name}(#{version_num})' > ../../version.txt")
  end

  desc "Build release version of app"
  lane :build do
    keystore_props = load_keystore_properties

    # Compile release version of code
    gradle(
      task: "clean assembleRelease",
      flags: "-Dorg.gradle.internal.http.socketTimeout=120000 -Dorg.gradle.internal.http.connectionTimeout=120000",
      properties: {
        "android.injected.signing.store.file" => keystore_props['storeFile'],
        "android.injected.signing.store.password" => keystore_props['storePassword'],
        "android.injected.signing.key.alias" => keystore_props['keyAlias'],
        "android.injected.signing.key.password" => keystore_props['keyPassword']
      }
    )
  end

  desc "Submit already built app to Internal Track"
  lane :alpha do
    # Copy changelog for upload
    sh("mkdir -p ./metadata/android/en-GB/changelogs")
    sh("cp ../../Changelog.txt ./metadata/android/en-GB/changelogs/#{android_get_version_code}.txt")

    # Upload to Alpha
    upload_to_play_store(
      track: 'internal',
      version_code: android_get_version_code,
      apk: "app/build/outputs/apk/release/app-release.apk"
    )
  end

  desc "Submit already built app to Play Store"
  lane :release do
    # Copy changelog for upload
    sh("mkdir -p ./metadata/android/en-GB/changelogs")
    sh("cp ../../Changelog.txt ./metadata/android/en-GB/changelogs/#{android_get_version_code}.txt")

    # Upload to Release
    upload_to_play_store(
      track: 'production',
      version_code: android_get_version_code,
      apk: "app/build/outputs/apk/release/app-release.apk"
    )
  end
end
