default_platform(:ios)

platform :ios do

  desc "Create a new keychain on CI to install certs"
  lane :keychain do
    create_keychain(
      name: "CI",
      password: ENV["MATCH_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false
    )

    match(
      type: "appstore",
      git_url: ENV["git_url"],
      readonly: true,
      keychain_name: "CI",
      keychain_password: ENV["MATCH_PASSWORD"]
    )

    sh("security list-keychains -d user")
    sh("security default-keychain -d user")
    sh("security find-identity -v -p codesigning CI")
  end

  desc "Submit a new build to Testflight"
  lane :alpha do
    # Increment build number
    increment_build_number

    # Compile release version of code
    build_app(scheme: "flare")

    # If compiles then commit build change
    git_commit(
      path: ".",
      message: "iOS Alpha Release"
    )

    # Upload to Testflight
    # TODO: UPLOAD!
  end

  desc "Submit a new build to App Store"
  lane :release do |options|
    # Increment VersionCode & VersionName
    increment_build_number
    increment_version_number(
      version_number: options[:version]
    )

    # Compile release version of code
    build_app(scheme: "flare")

    # If compiles then commit build change
    git_commit(
      path: ".",
      message: "iOS Production Release"
    )

    # Upload to Play Store (Release Channel)
    # TODO: UPLOAD!
  end
end
