default_platform(:ios)

platform :ios do
  desc "Submit a new build to Testflight"
  lane :alpha do
    # Increment build number
    increment_build_number

    # Compile release version of code
    build_app(scheme: "flare")

    # If compiles then commit build change
    git_commit(
      path: ".",
      message: "iOS Alpha Release"
    )

    # Upload to Testflight
    # TODO: UPLOAD!
  end

  desc "Submit a new build to App Store"
  lane :release do |options|
    # Increment VersionCode & VersionName
    increment_build_number
    increment_version_number(
      version_number: options[:version]
    )

    # Compile release version of code
    build_app(scheme: "flare")

    # If compiles then commit build change
    git_commit(
      path: ".",
      message: "iOS Production Release"
    )

    # Upload to Play Store (Release Channel)
    # TODO: UPLOAD!
  end
end
