default_platform(:android)

platform :android do
  desc "Increase version number"
  lane :bump do |options|
    android_set_version_code
    if options[:version].nil?
      android_set_version_name(
        version_name: options[:version]
      )
    end
  end

  desc "Submit a new build to Play Store (Alpha Track)"
  lane :build do
    # Compile release version of code
    gradle(task: "clean bundleRelease")
  end
end
