name: Deploy iOS

on: [push]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30

    env:
      DEVELOPER_DIR: /Applications/Xcode_12.app

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Node
        uses: actions/setup-node@v1

      - name: Install Dependencies
        run: npm install

      - name: Install Fastlane
        run: brew install fastlane

      - name: Create Keychain
        run: |
          security create-keychain -p ${{ secrets.MATCH_PASSWORD }} build.keychain
          security list-keychains -s ~/Library/Keychains/build.keychain
          security default-keychain -s ~/Library/Keychains/build.keychain
          security unlock-keychain -p ${{ secrets.MATCH_PASSWORD }} ~/Library/Keychains/build.keychain

      - name: Install iOS Credentials
        run: cd ios && fastlane match appstore --readonly --verbose --git_url https://${{ secrets.CERTS_ACCESS_TOKEN }}@github.com/flare-kcl/ios-certs --keychain_name build.keychain --keychain_password ${{ secrets.MATCH_PASSWORD }}
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

      - name: Cache Pods
        uses: actions/cache@v1
        id: podcache
        with:
          path: Pods
          key: pods-${{ hashFiles('**/Podfile.lock') }}

      - name: Update Pods
        run: cd ios && pod install

      - name: Deploy Alpha
        run: fastlane alpha
