name: Deploy iOS

on: [push]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30

    env:
      DEVELOPER_DIR: /Applications/Xcode_12.app

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Node
        uses: actions/setup-node@v1

      - name: Install Dependencies
        run: npm install

      - name: Cache Pods
        uses: actions/cache@v1
        id: podcache
        with:
          path: ios/Pods
          key: pods-${{ hashFiles('**/Podfile.lock') }}

      - name: Update Pods
        run: |
          gem update cocoapods xcodeproj
          cd ios && pod install && cd ..

      - name: Install Fastlane
        run: brew install fastlane

      - name: Install Credentials
        run: fastlane match appstore
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

      - name: Deploy Alpha
        run: cd ios && fastlane alpha
