name: Deployment

on:
  push:
    branches: [develop]
  workflow_dispatch:
    inputs:

jobs:
  # Version Management
  versions:
    name: 'Version Management'
    runs-on: macos-latest
    timeout-minutes: 15

    # Support [skip-ci] in commit message
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"

    env:
      DEVELOPER_DIR: /Applications/Xcode_12.app

    steps:
      - name: Turnstyle
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Get tag from commit
        id: rawTag
        run: |
          echo ::set-output name=rawTag::$(git --no-pager tag --points-at HEAD)
          echo ::set-output name=defaultTag::"ALPHA"
          git --no-pager tag --points-at HEAD

      # Select 1.3.3 from "v1.3.3"
      - name: Extract version from tag
        id: tagName
        run: echo ::set-output name=version::$(node -e "console.log(/v(.*)/.exec('${{ steps.rawTag.outputs.rawTag || steps.rawTag.outputs.defaultTag }}')[1])")

      - name: Using Tag (Debug)
        run: echo ${{steps.tagName.outputs.version}}

      - name: Node
        uses: actions/setup-node@v1

      - name: Install Fastlane
        run: brew install fastlane

      - name: Increment iOS Version
        run: cd ios && fastlane bump version:${{ steps.tagName.outputs.version }} && cd ..

      - name: Increment Android Version
        run: cd android && fastlane bump version:${{ steps.tagName.outputs.version }} && cd ..

      - name: Print Version Changes (Debug)
        run: git --no-pager diff

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Generate Production .env file
        if: github.ref == 'refs/heads/main'
        run: |
          pip install dump-env
          dump-env --template=./.env.template > .env
        env:
          BASE_API_URL: ${{ secrets.PROD_API_URL }}
          API_AUTH_TOKEN: ${{ secrets.PROD_AUTH_TOKEN }}
          SENTRY_DTN: ${{ secrets.SENTRY_DTN }}

      # Cache artifacts for future jobs
      - uses: actions/upload-artifact@v2
        with:
          name: build-config
          path: |
            ./.env
            ./android/app/build.gradle
            ./ios/flare.xcodeproj/project.pbxproj
            ./ios/flare/Info.plist
            ./version.txt

  # Build script to for iOS apps
  ios:
    name: 'Build iOS App'
    needs: versions
    runs-on: macos-latest
    timeout-minutes: 90

    env:
      DEVELOPER_DIR: /Applications/Xcode_12.app

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Node
        uses: actions/setup-node@v1

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - uses: actions/download-artifact@v2
        with:
          name: build-config

      - name: Generate Production .env file
        if: github.ref == 'refs/heads/main'
        run: |
          pip install dump-env
          dump-env --template=./.env.template > .env
        env:
          BASE_API_URL: ${{ secrets.PROD_API_URL }}
          API_AUTH_TOKEN: ${{ secrets.PROD_AUTH_TOKEN }}
          SENTRY_DTN: ${{ secrets.SENTRY_DTN }}

      - name: Generate Develop .env file
        if: github.ref == 'refs/heads/develop'
        run: |
          pip install dump-env
          dump-env --template=./.env.template > .env
        env:
          BASE_API_URL: ${{ secrets.DEV_API_URL }}
          API_AUTH_TOKEN: ${{ secrets.DEV_AUTH_TOKEN }}
          SENTRY_DTN: ${{ secrets.SENTRY_DTN }}

      - name: Install Dependencies
        run: npm install

      - name: Install Fastlane
        run: brew install fastlane

      - name: Create Keychain
        run: |
          security create-keychain -p ${{ secrets.MATCH_PASSWORD }} build.keychain
          security list-keychains -s ~/Library/Keychains/build.keychain
          security default-keychain -s ~/Library/Keychains/build.keychain
          security unlock-keychain -p ${{ secrets.MATCH_PASSWORD }} ~/Library/Keychains/build.keychain

      - name: Install iOS Credentials
        run: cd ios && fastlane match appstore --readonly --verbose --git_url https://${{ secrets.CERTS_ACCESS_TOKEN }}@github.com/flare-kcl/ios-certs --keychain_name build.keychain --keychain_password ${{ secrets.MATCH_PASSWORD }} && cd ..
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

      - name: Update Pods
        run: cd ios && pod install

      - name: Build Release App
        run: cd ios && fastlane build --verbose
        env:
          KEYCHAIN_PATH: ~/Library/Keychains/build.keychain
          KEYCHAIN_PASS: ${{ secrets.MATCH_PASSWORD }}

      - name: Cache iOS Build
        uses: actions/upload-artifact@v2
        with:
          name: ios-build
          path: |
            ./ios
            !./ios/Pods

  # Build script to for Android apps
  android:
    name: 'Build Android App'
    needs: versions
    runs-on: macos-latest
    timeout-minutes: 90

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - uses: actions/download-artifact@v2
        with:
          name: build-config

      - name: Generate Production .env file
        if: github.ref == 'refs/heads/main'
        run: |
          pip install dump-env
          dump-env --template=./.env.template > .env
        env:
          BASE_API_URL: ${{ secrets.PROD_API_URL }}
          API_AUTH_TOKEN: ${{ secrets.PROD_AUTH_TOKEN }}
          SENTRY_DTN: ${{ secrets.SENTRY_DTN }}

      - name: Generate Develop .env file
        if: github.ref == 'refs/heads/develop'
        run: |
          pip install dump-env
          dump-env --template=./.env.template > .env
        env:
          BASE_API_URL: ${{ secrets.DEV_API_URL }}
          API_AUTH_TOKEN: ${{ secrets.DEV_AUTH_TOKEN }}
          SENTRY_DTN: ${{ secrets.SENTRY_DTN }}

      - name: Install Dependencies
        run: npm install

      - name: Install JDK 8
        uses: joschi/setup-jdk@v2
        with:
          java-version: 'openjdk8'
          architecture: 'x64'

      - name: Install Fastlane
        run: brew install fastlane

      - name: Install Android Credentials
        run: |
          cd android/app
          echo "${{ secrets.KEY_STORE }}" | base64 --decode > release.keystore
          echo "${{ secrets.KEY_STORE_CONFIG }}" > keystore.properties
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > google-services.json
          cd ../fastlane
          echo "${{ secrets.ANDROID_API_KEY }}" | base64 --decode > api.json
          cd ../../

      - name: Build Release App
        run: cd android && fastlane build --verbose && cd ..

      - name: Cache Android Build
        uses: actions/upload-artifact@v2
        with:
          name: android-build
          path: |
            ./android
            !./android/.gradle
            !./android/fastlane/api.json
            !./android/app/build/intermediates
            !./android/app/keystore.properties
            !./android/app/release.keystore

  # Script to deploy each platform and package as release
  packaging:
    name: 'Packaging'
    needs:
      - android
      - ios
    runs-on: macos-latest
    timeout-minutes: 120

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Install Fastlane
        run: brew install fastlane

      - name: Create Keychain
        run: |
          security create-keychain -p ${{ secrets.MATCH_PASSWORD }} build.keychain
          security list-keychains -s ~/Library/Keychains/build.keychain
          security default-keychain -s ~/Library/Keychains/build.keychain
          security unlock-keychain -p ${{ secrets.MATCH_PASSWORD }} ~/Library/Keychains/build.keychain

      - name: Install iOS Credentials
        run: |
          cd ios
          fastlane match appstore --readonly --verbose --git_url https://${{ secrets.CERTS_ACCESS_TOKEN }}@github.com/flare-kcl/ios-certs --keychain_name build.keychain --keychain_password ${{ secrets.MATCH_PASSWORD }}
          echo "${{ secrets.IOS_API_KEY }}" | base64 --decode > api.json
          cd ..
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

      - name: Install Android Credentials
        run: |
          cd android/app
          echo "${{ secrets.KEY_STORE }}" | base64 --decode > release.keystore
          echo "${{ secrets.KEY_STORE_CONFIG }}" > keystore.properties
          cd ../fastlane
          echo "${{ secrets.ANDROID_API_KEY }}" | base64 --decode > api.json
          cd ../../

      - uses: olegtarasov/get-tag@v2
        id: tagName
        with:
          # Select 1.3.3 from "v1.3.3"
          tagRegex: 'v(.*)'

      - uses: actions/download-artifact@v2
        with:
          name: build-config

      - uses: actions/download-artifact@v2
        with:
          name: ios-build
          path: ./ios

      - uses: actions/download-artifact@v2
        with:
          name: android-build
          path: ./android

      - name: Print version Changes (Debug)
        run: git --no-pager diff

      - name: Deploy iOS App to Alpha Testers
        if: github.ref == 'refs/heads/develop'
        run: cd ios && fastlane alpha --verbose && cd ..

      - name: Deploy iOS App to App Store
        if: github.ref == 'refs/heads/main'
        run: cd ios && fastlane release --verbose && cd ..

      - name: Deploy Android App to Internal Track
        if: github.ref == 'refs/heads/develop'
        run: cd android && fastlane alpha --verbose && cd ..

      - name: Deploy Android App to Play Store
        if: github.ref == 'refs/heads/main'
        run: cd android && fastlane release --verbose && cd ..

      - name: Get Release Version
        id: version
        run: echo ::set-output name=version::$(cat ./version.txt)

      - name: Get Latest Changelog
        id: changelog
        run: echo ::set-output name=changelog::$(cat ./Changelog.txt)

      - name: Setup Git
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'flare@torchbox.com'

      - name: Commit Changes (Develop)
        if: github.ref == 'refs/heads/develop'
        run: |
          git checkout develop
          git add ./ios/flare.xcodeproj ./ios/flare/Info.plist ./android/app/build.gradle
          git commit -m "Version Bump [skip-ci]"
          git tag -a "${{ steps.version.outputs.version }}" -m "${{ steps.version.outputs.version }}"
          git --no-pager push -u origin develop

      - name: Commit Changes (Main)
        if: github.ref == 'refs/heads/main'
        run: |
          git checkout main

          git add ./ios/flare.xcodeproj ./ios/flare/Info.plist ./android/app/build.gradle
          git stash

          git stash apply
          git add .
          git commit -m "Version Bump [skip-ci]"
          git tag -a "${{ steps.version.outputs.version }}" -m "${{ steps.version.outputs.version }}"
          git --no-pager push -u origin main

          git checkout develop
          git stash apply
          git add .
          git commit -m "Version Bump [skip-ci]"
          git --no-pager push -u origin develop

          git checkout main

      - name: Get commit hash
        id: commitPush
        run: echo ::set-output name=commit::$(git rev-parse HEAD)

      - name: Create Alpha Release
        if: github.ref == 'refs/heads/develop'
        id: create_alpha_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: Alpha ${{ steps.version.outputs.version }}
          commitish: ${{ steps.commitPush.outputs.commit }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: true
          prerelease: true

      - name: Create Prod Release
        if: github.ref == 'refs/heads/main'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: Release ${{ steps.version.outputs.version }}
          commitish: ${{ steps.commitPush.outputs.commit }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false

      - name: Attach iOS App (Github Release)
        id: upload-ios-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url || steps.create_alpha_release.outputs.upload_url }}
          asset_path: ./ios/flare.ipa
          asset_name: FLARe.ipa
          asset_content_type: application/zip

      - name: Attach Android App (Github Release)
        id: upload-android-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url || steps.create_alpha_release.outputs.upload_url }}
          asset_path: ./android/app/build/outputs/apk/release/app-release.apk
          asset_name: FLARe.apk
          asset_content_type: application/vnd.android.package-archive
