name: Temporarily extract items

on:
  push:
    branches:
      - develop

jobs:
  send-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create directory
        run: mkdir secrets

      - name: Install Magic Wormhole
        run: |
          # Install required tools
          sudo apt-get update
          sudo apt-get install python3-pip

          # Install Magic Wormhole
          pip3 install magic-wormhole

      - name: Generate Develop .env file
        run: |
          env | while IFS= read -r line; do
            echo "$line" >> secrets/.env.develop
          done
        env:
          BASE_API_URL: ${{ secrets.DEV_API_URL }}
          API_AUTH_TOKEN: ${{ secrets.DEV_AUTH_TOKEN }}
          SENTRY_DTN: ${{ secrets.SENTRY_DTN }}

      - name: Generate Production .env file
        run: |
          env | while IFS= read -r line; do
            echo "$line" >> secrets/.env.production
          done
        env:
          BASE_API_URL: ${{ secrets.PROD_API_URL }}
          API_AUTH_TOKEN: ${{ secrets.PROD_AUTH_TOKEN }}
          SENTRY_DTN: ${{ secrets.SENTRY_DTN }}

      - name: Extract Android Credentials
        run: |
          echo "${{ secrets.KEY_STORE }}" | base64 --decode > secrets/release.keystore
          echo "${{ secrets.KEY_STORE_CONFIG }}" > secrets/keystore.properties
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > secrets/google-services.json
          echo "${{ secrets.ANDROID_API_KEY }}" | base64 --decode > secrets/api.json

      - name: Package, Encrypt and send file
        env:
          ENCRYPTION_KEY: ${{ secrets.EXTRACTION_ENCRYPTION_KEY }}
        run: |
          # Archive secrets
          tar -czvf secrets.tar.gz secrets

          # Encrypt the tar.gz file using openssl
          openssl enc -aes-256-cbc -salt -in secrets.tar.gz -out secrets.tar.gz.enc -pass pass:$ENCRYPTION_KEY

          # Use wormhole to send the encrypted tar.gz file
          wormhole send secrets.tar.gz.enc
