name: Runtime Tests

on:
  push:
    branches: [main, feature/11-asset-caching]
  pull_request:
    branches: [main]

jobs:
  ios:
    name: iOS Runtime Tests
    runs-on: macos-latest
    timeout-minutes: 30

    env:
      DEVELOPER_DIR: /Applications/Xcode_12.app

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Node
        uses: actions/setup-node@v1

      - name: Install Dependencies
        run: npm install

      - name: Install Detox globally
        run: npm install -g detox

      - name: Cache Pods
        uses: actions/cache@v1
        id: podcache
        with:
          path: ios/Pods
          key: pods-${{ hashFiles('**/Podfile.lock') }}

      - name: Update Pods
        run: |
          gem update cocoapods xcodeproj
          cd ios && pod install && cd ..
      - run: brew tap wix/brew
      - run: brew install applesimutils

      - name: Rebuild Detox framework
        run: detox clean-framework-cache && detox build-framework-cache

      - name: Build App via Detox
        run: npm run e2e:build:ios

      - name: Test iOS Runtime
        run: npm run e2e:test:ios
